In [70]:
import numpy as np
import os
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.models import Model
from keras.layers import Input, Conv2D, Conv2DTranspose, MaxPooling2D
from keras.layers import Concatenate
import matplotlib.pyplot as plt
import tensorflow as tf
import cv2


In [71]:

DIM = 512
EPOCHS = ...
PATIENCE = ...
BATCH_SIZE = ...
OPTIMIZER = "..."
N_CHANNELS = 3
N_CLASSES = 3
MODEL_NAME = "unet_multiclass.h5"


In [72]:
src_path = "saved_arrays_multiclass/"

train_images = np.load(src_path + "train_images.npy")
train_masks_one_hot = np.load(src_path + "train_masks.npy")
train_masks = np.argmax(train_masks_one_hot, axis=-1)
train_masks = np.expand_dims(train_masks, axis=-1)
print(train_masks.shape)


val_images = np.load(src_path + "val_images.npy")
val_masks_one_hot = np.load(src_path + "val_masks.npy")
val_masks = np.argmax(val_masks_one_hot, axis=-1)
val_masks = np.expand_dims(val_masks, axis=-1)
print(val_masks.shape)

test_images = np.load(src_path + "test_images.npy")
test_masks_one_hot = np.load(src_path + "test_masks.npy")
test_masks = np.argmax(test_masks_one_hot, axis=-1)
test_masks = np.expand_dims(test_masks, axis=-1)
print(test_masks.shape)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[1 1 1 ... 0 0 0]
  [1 1 1 ... 0 0 0]
  [1 1 1 ... 0 0 0]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]]

 [[1 1 1 ... 0 0 0]
  [1 1 1 ... 0 0 0]
  [1 1 1 ... 0 0 0]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]]

 [[1 1 1 ... 0 0 0]
  [1 1 1 ... 0 0 0]
  [1 1 1 ... 0 0 0]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]]]
(858, 512, 512, 1)
[[[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0

In [73]:
train_images = train_images/255.0
val_images = val_images/255.0
test_images = test_images/255.0

In [74]:
checkpoint_path = "checkpoints"

if not os.path.exists(checkpoint_path):
    os.mkdir(checkpoint_path)

### UNET

In [75]:
def unet(sz, n_classes=3):
   """..."""
    return model

In [76]:

model = unet((DIM,DIM,3), n_classes=3)
#model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [77]:

model.compile(
    optimizer=OPTIMIZER,
    loss= tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=["..."],
)

In [78]:
model.summary()


Model: "model_7"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_8 (InputLayer)            [(None, 512, 512, 3) 0                                            
__________________________________________________________________________________________________
conv2d_189 (Conv2D)             (None, 512, 512, 8)  224         input_8[0][0]                    
__________________________________________________________________________________________________
conv2d_190 (Conv2D)             (None, 512, 512, 8)  584         conv2d_189[0][0]                 
__________________________________________________________________________________________________
max_pooling2d_42 (MaxPooling2D) (None, 256, 256, 8)  0           conv2d_190[0][0]                 
____________________________________________________________________________________________

In [79]:

def build_callbacks():
    checkpointer = [
          EarlyStopping(monitor="val_loss", patience=PATIENCE, restore_best_weights=True),
          ModelCheckpoint(checkpoint_path + '/' + MODEL_NAME,  monitor="val_loss", save_best_only=True)
    ]
    return checkpointer


In [80]:

model.fit(train_images, train_masks,  batch_size=BATCH_SIZE, verbose=1, epochs=EPOCHS, validation_data=(val_images, val_masks), callbacks = build_callbacks())


Epoch 1/500
108/108 [==============================] - 14s 107ms/step - loss: 0.8185 - accuracy: 0.6204 - val_loss: 0.7746 - val_accuracy: 0.6561
Epoch 2/500
108/108 [==============================] - 10s 95ms/step - loss: 0.7914 - accuracy: 0.6227 - val_loss: 0.7397 - val_accuracy: 0.6645
Epoch 3/500
108/108 [==============================] - 10s 94ms/step - loss: 0.7323 - accuracy: 0.6790 - val_loss: 0.6821 - val_accuracy: 0.7219
Epoch 4/500
108/108 [==============================] - 10s 94ms/step - loss: 0.6968 - accuracy: 0.6951 - val_loss: 0.6710 - val_accuracy: 0.7211
Epoch 5/500
108/108 [==============================] - 10s 94ms/step - loss: 0.6937 - accuracy: 0.6987 - val_loss: 0.6749 - val_accuracy: 0.7195
Epoch 6/500
108/108 [==============================] - 10s 95ms/step - loss: 0.6947 - accuracy: 0.6983 - val_loss: 0.6868 - val_accuracy: 0.7072
Epoch 7/500
108/108 [==============================] - 10s 94ms/step - loss: 0.6920 - accuracy: 0.6977 - val_loss: 0.6948 - val_a

In [81]:
def plot_img_and_masks(raw, mask):
    #mask is (512,512, 1)
    """...
    .
    ..."""

    #mask1 = np.argmax(mask, axis=-1)
    """...
   .
   ..."""

  
    return combined



In [82]:
sample_dir = "samples_multiclass" #where to save the predictions

if not os.path.exists(sample_dir):
    os.mkdir(sample_dir)

for i in range(test_images.shape[0]):
    test_img = test_images[i]
    test_mask = test_masks[i]
    combined = plot_img_and_masks(test_img, test_mask)
    cv2.imwrite(sample_dir + "/" + str(i) + '.jpg', combined * 255)


target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)
target_msk (512, 512, 3)


In [83]:

"""Quantitative measures"""

from evaluation_multiclass import mean_iou_test, dice_coeff, pixel_accuracy

print("TEST RESULTS for multiclass segmentation")
pred_masks_one_hot = model.predict(test_images) #(n examples,h,w,3)

#test_masks1 = np.argmax(test_masks, axis=-1) #(n examples,h,w)
pred_masks = np.argmax(pred_masks_one_hot, axis=-1)

iou, iou_classes = mean_iou_test(test_masks, pred_masks,num_classes=3)
print("mean iou", iou)
print(iou_classes)
dice, dice_classes = dice_coeff(test_masks, pred_masks,num_classes=3)
print("dice coeff.", dice)
print(dice_classes)
acc, acc_classes = pixel_accuracy(test_masks, pred_masks,num_classes=3)
print("pixel acc.", acc)
print(acc_classes)



TEST RESULTS for multiclass segmentation
mean iou 0.6305104021540022
[0.7761108147097731, 0.7975325184374651, 0.31788787331476853]
dice coeff. 0.7479093359093015
[0.8739441348839421, 0.8873636613047017, 0.48242021153926073]
pixel acc. 0.7137804462739031
[0.8619959719020343, 0.9143704947353689, 0.36497487218430613]
